version: '3.8'

services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    restart: on-failure
    deploy:
      replicas: 1
    tty: true
    stdin_open: true

# Define volumes to ensure no data is persisted between restarts
volumes:
  zipkin-data: