version: "3.9"

services:
  cambio-postgres:
    image: postgres:14
    container_name: cambio-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: cambio-service
    ports:
      - "5432:5432"
    volumes:
      - cambio-data:/var/lib/postgresql/data
volumes:
  cambio-data:
